/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/3DModel/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.6}>
        <mesh geometry={nodes.chess_board_board1_0.geometry} material={materials.board1} position={[0, 0.006, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.bishop3_pieces_w_0.geometry} material={materials.pieces_w} position={[-1.5, 0.301, 3.585]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.pawn15_pieces_w_0.geometry} material={materials.pieces_w} position={[-3.671, 0.301, 2.6]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.king1_pieces_w_0.geometry} material={materials.pieces_w} position={[0.578, 0.301, 3.585]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.rook3_pieces_w_0.geometry} material={materials.pieces_w} position={[-3.592, 0.301, 3.585]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={4.717} />
        <mesh geometry={nodes.queen1_pieces_w_0.geometry} material={materials.pieces_w} position={[-0.462, 0.301, 3.585]} rotation={[-Math.PI / 2, 0, Math.PI / 3]} scale={4.717} />
        <mesh geometry={nodes.pawn1_pieces_w_0.geometry} material={materials.pieces_w} position={[-2.58, 0.301, 2.6]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.pawn2_pieces_w_0.geometry} material={materials.pieces_w} position={[-1.49, 0.301, 2.6]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.pawn3_pieces_w_0.geometry} material={materials.pieces_w} position={[-0.473, 0.301, 2.6]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.pawn4_pieces_w_0.geometry} material={materials.pieces_w} position={[0.599, 0.301, 2.6]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.pawn5_pieces_w_0.geometry} material={materials.pieces_w} position={[1.67, 0.301, 2.6]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.pawn6_pieces_w_0.geometry} material={materials.pieces_w} position={[2.707, 0.301, 2.6]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.pawn7_pieces_w_0.geometry} material={materials.pieces_w} position={[3.761, 0.301, 2.6]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.knight3_pieces_w_0.geometry} material={materials.pieces_w} position={[-2.565, 0.301, 3.56]} rotation={[-Math.PI / 2, 0, -Math.PI / 6]} scale={4.717} />
        <mesh geometry={nodes.knight4_pieces_w_0.geometry} material={materials.pieces_w} position={[2.602, 0.301, 3.56]} rotation={[-Math.PI / 2, 0, 0.262]} scale={4.717} />
        <mesh geometry={nodes.bishop1_pieces_w_0.geometry} material={materials.pieces_w} position={[1.612, 0.301, 3.585]} rotation={[-Math.PI / 2, 0, -1.309]} scale={4.717} />
        <mesh geometry={nodes.rook1_pieces_w_0.geometry} material={materials.pieces_w} position={[3.707, 0.301, 3.585]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.bishop4_pieces_b_0.geometry} material={materials.pieces_b} position={[-1.534, 0.301, -3.716]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.pawn16_pieces_b_0.geometry} material={materials.pieces_b} position={[-3.621, 0.301, -2.584]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.king2_pieces_b_0.geometry} material={materials.pieces_b} position={[0.537, 0.301, -3.671]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.rook4_pieces_b_0.geometry} material={materials.pieces_b} position={[-3.648, 0.301, -3.716]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.queen2_pieces_b_0.geometry} material={materials.pieces_b} position={[-0.496, 0.301, -3.716]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.pawn8_pieces_b_0.geometry} material={materials.pieces_b} position={[-2.538, 0.301, -2.584]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={4.717} />
        <mesh geometry={nodes.pawn9_pieces_b_0.geometry} material={materials.pieces_b} position={[-1.53, 0.301, -2.584]} rotation={[-Math.PI / 2, 0, -Math.PI / 6]} scale={4.717} />
        <mesh geometry={nodes.pawn10_pieces_b_0.geometry} material={materials.pieces_b} position={[-0.471, 0.301, -2.584]} rotation={[-Math.PI / 2, 0, -Math.PI / 6]} scale={4.717} />
        <mesh geometry={nodes.pawn11_pieces_b_0.geometry} material={materials.pieces_b} position={[0.548, 0.301, -2.584]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={4.717} />
        <mesh geometry={nodes.pawn12_pieces_b_0.geometry} material={materials.pieces_b} position={[1.607, 0.301, -2.584]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.pawn13_pieces_b_0.geometry} material={materials.pieces_b} position={[2.679, 0.301, -2.584]} rotation={[-Math.PI / 2, 0, -Math.PI / 6]} scale={4.717} />
        <mesh geometry={nodes.pawn14_pieces_b_0.geometry} material={materials.pieces_b} position={[3.683, 0.301, -2.584]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.knight1_pieces_b_0.geometry} material={materials.pieces_b} position={[2.623, 0.301, -3.716]} rotation={[-Math.PI / 2, 0, -2.618]} scale={4.717} />
        <mesh geometry={nodes.bishop2_pieces_b_0.geometry} material={materials.pieces_b} position={[1.588, 0.301, -3.716]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.rook2_pieces_b_0.geometry} material={materials.pieces_b} position={[3.684, 0.301, -3.716]} rotation={[-Math.PI / 2, 0, 0]} scale={4.717} />
        <mesh geometry={nodes.knight2_pieces_b_0.geometry} material={materials.pieces_b} position={[-2.66, 0.301, -3.716]} rotation={[-Math.PI / 2, 0, 2.356]} scale={4.717} />
      </group>
    </group>
  )
}

useGLTF.preload('/3DModel/scene.gltf')
