/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ChessBoardModel/boardModel.gltf')
  return (
    <group {...props} dispose={null} scale={20} >
      <mesh geometry={nodes.Object_5.geometry} material={materials.board} position={[0, 0.01, 0]} rotation={[0, Math.PI / 2, 0]} scale={[1, 0.067, 1]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.black} position={[0.015, 0.029, 0.118]} rotation={[-Math.PI, 0, 0]} scale={[-0.01, 0.01, 0.01]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.white} position={[0.015, 0.029, -0.118]} rotation={[-Math.PI, 0, 0]} scale={[-0.01, 0.01, 0.01]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.black} position={[-0.084, 0.028, 0.118]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.black} position={[0.085, 0.028, 0.118]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.white} position={[-0.085, 0.028, -0.118]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.white} position={[0.083, 0.028, -0.118]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.black} position={[-0.121, 0.028, 0.084]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.black} position={[-0.085, 0.028, 0.084]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.black} position={[-0.051, 0.028, 0.083]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.black} position={[-0.017, 0.028, 0.084]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.black} position={[0.016, 0.028, 0.084]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.black} position={[0.05, 0.028, 0.084]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.black} position={[0.084, 0.028, 0.083]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.black} position={[0.117, 0.028, 0.084]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.white} position={[0.115, 0.028, -0.084]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.white} position={[0.083, 0.028, -0.084]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.white} position={[0.049, 0.028, -0.085]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.white} position={[0.017, 0.028, -0.084]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.white} position={[-0.018, 0.028, -0.084]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.white} position={[-0.051, 0.028, -0.084]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.white} position={[-0.086, 0.028, -0.084]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.white} position={[-0.121, 0.028, -0.082]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.black} position={[-0.017, 0.029, 0.117]} rotation={[-Math.PI, 0, 0]} scale={[-0.01, 0.01, 0.01]} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.white} position={[-0.019, 0.029, -0.118]} rotation={[-Math.PI, 0, 0]} scale={[-0.01, 0.01, 0.01]} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.black} position={[-0.05, 0.027, 0.119]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.black} position={[0.05, 0.027, 0.117]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.white} position={[-0.053, 0.027, -0.117]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.white} position={[0.047, 0.027, -0.118]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.black} position={[-0.12, 0.028, 0.117]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.black} position={[0.117, 0.028, 0.119]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_67.geometry} material={materials.white} position={[-0.12, 0.028, -0.118]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
      <mesh geometry={nodes.Object_69.geometry} material={materials.white} position={[0.115, 0.028, -0.117]} rotation={[-Math.PI, 0, 0]} scale={[-0.009, 0.009, 0.009]} />
    </group>
  )
}

useGLTF.preload('/ChessBoardModel/scene.gltf')
